Create question1.java
Codechef-SRM-NCR-Chapter/30-DaysOfCode-March-2021 pull request #59
Opened 2021-03-17 19:02 UTC by digvijay160

2021-03-17 19:07 UTC, Tanish2002 commented
solution to second problem is missing

2021-03-17 19:07 UTC, Tanish2002 requested changes
solution to second problem is missing

2021-03-18 04:59 UTC, bhattcodes commented
@digvijay160 It would be better if you will make 2 separate files for different questions, you done both question in one file, Fix it.

2021-03-18 05:52 UTC, merged

2021-03-18 05:52 UTC, Tanish2002 commented
Good Job!